#define IDB_XXL                         401
#define IDB_XXD                         402
#define IDB_XXS                         403
#define IDB_WCL                         410
#define IDB_WPL                         411
#define IDB_WNL                         412
#define IDB_WBL                         413
#define IDB_WRL                         414
#define IDB_WQL                         415
#define IDB_WKL                         416
#define IDB_BCL                         420
#define IDB_BPL                         421
#define IDB_BNL                         422
#define IDB_BBL                         423
#define IDB_BRL                         424
#define IDB_BQL                         425
#define IDB_BKL                         426
#define IDB_WCS                         430
#define IDB_WPS                         431
#define IDB_WNS                         432
#define IDB_WBS                         433
#define IDB_WRS                         434
#define IDB_WQS                         435
#define IDB_WKS                         436
#define IDB_BCS                         440
#define IDB_BPS                         441
#define IDB_BNS                         442
#define IDB_BBS                         443
#define IDB_BRS                         444
#define IDB_BQS                         445
#define IDB_BKS                         446

#define IDB_P_0                         490
#define IDB_P_1                         491
#define IDB_P_2                         492
#define IDB_P_1S                        493
#define IDB_P_1R                        494
