#define IDB_XXL                         400
#define IDB_WPL                         401
#define IDB_WNL                         402
#define IDB_WBL                         403
#define IDB_WRL                         404
#define IDB_WQL                         405
#define IDB_WKL                         406
#define IDB_BPL                         411
#define IDB_BNL                         412
#define IDB_BBL                         413
#define IDB_BRL                         414
#define IDB_BQL                         415
#define IDB_BKL                         416
#define IDB_XXD                         420
#define IDB_WPD                         421
#define IDB_WND                         422
#define IDB_WBD                         423
#define IDB_WRD                         424
#define IDB_WQD                         425
#define IDB_WKD                         426
#define IDB_BPD                         431
#define IDB_BND                         432
#define IDB_BBD                         433
#define IDB_BRD                         434
#define IDB_BQD                         435
#define IDB_BKD                         436
#define IDB_WPS                         441
#define IDB_WNS                         442
#define IDB_WBS                         443
#define IDB_WRS                         444
#define IDB_WQS                         445
#define IDB_WKS                         446
#define IDB_BPS                         451
#define IDB_BNS                         452
#define IDB_BBS                         453
#define IDB_BRS                         454
#define IDB_BQS                         455
#define IDB_BKS                         456

#define IDB_WCL                         457
#define IDB_WCD                         458
#define IDB_WCS                         459
#define IDB_BCL                         460
#define IDB_BCD                         461
#define IDB_BCS                         462

#define IDB_P_0                         470
#define IDB_P_1                         471
#define IDB_P_2                         472
#define IDB_P_1S                        473
#define IDB_P_1R                        474
