#define IDB_PEGB                        901
#define IDB_PEGW                        902
#define IDB_PEGBF                       903
#define IDB_PEGWF                       904
#define IDB_PEG1                        911
#define IDB_PEG2                        912
#define IDB_PEG3                        913
#define IDB_PEG4                        914
#define IDB_PEG5                        915
#define IDB_PEG6                        916
#define IDB_PEG7                        917
#define IDB_PEG8                        918
#define IDB_PEG1F                       921
#define IDB_PEG2F                       922
#define IDB_PEG3F                       923
#define IDB_PEG4F                       924
#define IDB_PEG5F                       925
#define IDB_PEG6F                       926
#define IDB_PEG7F                       927
#define IDB_PEG8F                       928
