#define IDB_PEGB                        601
#define IDB_PEGW                        602
#define IDB_PEGBF                       603
#define IDB_PEGWF                       604
#define IDB_PEG1                        611
#define IDB_PEG2                        612
#define IDB_PEG3                        613
#define IDB_PEG4                        614
#define IDB_PEG5                        615
#define IDB_PEG6                        616
#define IDB_PEG7                        617
#define IDB_PEG8                        618
#define IDB_PEG1F                       621
#define IDB_PEG2F                       622
#define IDB_PEG3F                       623
#define IDB_PEG4F                       624
#define IDB_PEG5F                       625
#define IDB_PEG6F                       626
#define IDB_PEG7F                       627
#define IDB_PEG8F                       628
